version: 2

jobs:
  build:
    docker:
      - image: jrobic/node-puppeteer-deps:10.15.3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "example/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Setup Dependencies
          working_directory: ~/repo/example
          command: npm install

      - save_cache:
          paths:
            - example/node_modules
          key: v1-dependencies-{{ checksum "example/package.json" }}

      - run:
          name: Run app
          working_directory: ~/repo/example
          command: npm start
          background: true

      - run:
          name: Run Test
          working_directory: ~/repo/example
          command: |
            CI=true npm run test -- --forceExit

      - run:
          name: Run Build with React Snap
          working_directory: ~/repo/example
          command: npm run build